image:
  repository: cassandra
  tag: "4.1"
  pullPolicy: IfNotPresent

auth:
  username: "cassandra"
  password: "cassandra_password"

cluster:
  name: "classroom-cluster"

storage:
  className: "" # Vacío = usa la StorageClass default del cluster (local-path en k3d, gp3 en EKS)
  size: 2Gi

resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    memory: "1536Mi"

jvm:
  maxHeapSize: "512M"
  heapNewSize: "128M"

keda:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 600
  minReplicaCount: 0
  maxReplicaCount: 1
  threshold: "60"
  activationThreshold: "60"
  metricName: "network_traffic_bytes"
  queryWindow: "1m"
  serverAddress: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"

# Python rellenará esto
instances: []
