apiVersion: v1
kind: Secret
metadata:
  name: shared-credentials
type: Opaque
data:
  cassandra-username: {{ .Values.auth.username | toString | b64enc | quote }}
  cassandra-password: {{ .Values.auth.password | toString | b64enc | quote }}
