image:
  repository: mongo
  tag: "7.0"
  pullPolicy: IfNotPresent

# Credenciales compartidas para toda la clase
auth:
  rootUsername: "alumno"
  rootPassword: "password"
  database: "practica_db"

storage:
  className: "" # Vacío = usa la StorageClass default del cluster (local-path en k3d, gp3 en EKS)
  size: 1Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    memory: "512Mi"

keda:
  enabled: true
  pollingInterval: 300
  cooldownPeriod:  600
  minReplicaCount: 0
  maxReplicaCount: 1
  threshold: "60"
  activationThreshold: "60"
  metricName: "network_traffic_bytes"
  queryWindow: "5m"
  serverAddress: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"

# Python rellenará esto
instances: []
