{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ include "db-manager-app.namespace" . }}
  labels:
    {{- include "db-manager-app.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
