image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

# Credenciales compartidas para toda la clase
auth:
  username: "alumno"
  password: "clase_password"
  rootPassword: "root_password"
  database: "practica_db"

storage:
  className: "" # Vacío = usa la StorageClass default del cluster (standard en Minikube, gp3 en EKS)
  size: 1Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    memory: "512Mi"

# Python rellenará esto
instances: []